import React, { useEffect, useState } from 'react';
import { useApp } from '../../../../core/providers/AppProvider';
import { AdminLayout } from '../shared/AdminLayout';
import { Button, ConfirmDialog, FilterPill, Input, Modal, Pagination, SearchInput, TextArea } from '../../../shared/components/ui';
import { usePagination } from '../../../shared/hooks/usePagination';
import { Film, Plus, Edit, Trash2, Play, Check, Upload, Video, Loader2 } from 'lucide-react';
import { VideoItem } from '../../../../../types';
import { useCloudinaryUpload } from '../../../shared/hooks/useCloudinaryUpload';
import { cloudinaryService } from '../../../../../lib/services/cloudinary.service';
import { isValidHttpUrl } from '../../../../../utils/helpers';

// Eager poster generated at upload: 16:9, 640px wide, frame at 5s.
// Adjust the frame offset (so_5) or size here to change the auto thumbnail.
const VIDEO_POSTER_EAGER = 'w_640,h_360,c_fill,so_5/jpg';

export const AdminVideosView: React.FC = () => {
  const { videos, addVideoItem, updateVideoItem, deleteVideoItem, showToast } = useApp();
  const [deleteConfirm, setDeleteConfirm] = useState<{ id: string; title: string } | null>(null);

  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('all');
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingVideo, setEditingVideo] = useState<VideoItem | null>(null);

  // Cloudinary upload hooks
  const { uploadFile: uploadVideo, uploadProgress: videoUploadProgress, isUploading: isVideoUploading, uploadError: videoUploadError, resetUpload: resetVideoUpload } = useCloudinaryUpload();
  const { uploadFile: uploadThumbnail, uploadProgress: thumbnailUploadProgress, isUploading: isThumbnailUploading, uploadError: thumbnailUploadError, resetUpload: resetThumbnailUpload } = useCloudinaryUpload();

  // Form State
  const [title, setTitle] = useState('');
  const [videoUrl, setVideoUrl] = useState('');
  const [thumbnailUrl, setThumbnailUrl] = useState('');
  const [duration, setDuration] = useState('04:30');
  const [category, setCategory] = useState('Documentary');
  const [description, setDescription] = useState('');

  // Cloudinary metadata state
  const [videoMetadata, setVideoMetadata] = useState<any>(null);
  const [thumbnailMetadata, setThumbnailMetadata] = useState<any>(null);

  // Helper to check if URL is direct video file/data
  const isDirectVideo = (url: string) => {
    if (!url) return false;
    return url.startsWith('data:video') || url.startsWith('blob:') || url.match(/\.(mp4|webm|ogg|mov)$/i);
  };

  // Cloudinary Video File Upload handler
  const handleVideoFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      // Validate video file type
      if (!file.type.startsWith('video/')) {
        showToast('Please select a valid video file (MP4, WEBM, OGG, MOV).');
        return;
      }
      
      try {
        resetVideoUpload();
        // Request an eager poster frame (5s in, 16:9, 640px) so the thumbnail
        // never lands on a black 0:00 frame and is pre-generated by Cloudinary.
        const result = await uploadVideo(file, {
          folder: 'blht/videos',
          resourceType: 'video',
          eager: VIDEO_POSTER_EAGER
        });
        
        setVideoUrl(result.secure_url);
        setVideoMetadata(result);
        
        // Auto-populate duration from Cloudinary
        if (result.duration) {
          setDuration(cloudinaryService.formatDuration(result.duration));
        }
        
        // Auto-generate thumbnail from the eager poster derivative
        const eagerPoster = result.eager?.find(d => d.format === 'jpg');
        if (eagerPoster?.secure_url) {
          setThumbnailUrl(eagerPoster.secure_url);
        } else if (result.secure_url) {
          // Fallback to Cloudinary's on-the-fly poster URL
          const posterUrl = result.secure_url.replace(/\.(mp4|webm|ogg|mov)$/i, '.jpg');
          setThumbnailUrl(posterUrl);
        }

        showToast(`Video uploaded to Cloudinary successfully! Verify the URL before publishing: ${result.secure_url}`);
      } catch (error) {
        console.error('Video upload failed:', error);
        showToast('Video upload failed. Please try again.');
      }
    }
  };

  // Cloudinary Thumbnail Upload handler
  const handleThumbnailUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      // Validate image file type
      if (!file.type.startsWith('image/')) {
        showToast('Please select a valid image file (PNG, JPG, WEBP).');
        return;
      }
      
      try {
        resetThumbnailUpload();
        const result = await uploadThumbnail(file, {
          folder: 'blht/thumbnails',
          resourceType: 'image'
        });
        
        setThumbnailUrl(result.secure_url);
        setThumbnailMetadata(result);
        showToast(`Thumbnail uploaded to Cloudinary successfully! Verify the URL before publishing: ${result.secure_url}`);
      } catch (error) {
        console.error('Thumbnail upload failed:', error);
        showToast('Thumbnail upload failed. Please try again.');
      }
    }
  };

  const handleOpenAddModal = () => {
    setEditingVideo(null);
    setTitle('');
    setVideoUrl('');
    setThumbnailUrl('');
    setDuration('05:00');
    setCategory('Documentary');
    setDescription('');
    setVideoMetadata(null);
    setThumbnailMetadata(null);
    resetVideoUpload();
    resetThumbnailUpload();
    setIsModalOpen(true);
  };

  const handleOpenEditModal = (vid: VideoItem) => {
    setEditingVideo(vid);
    setTitle(vid.title);
    setVideoUrl(vid.videoUrl || (vid.youtubeId ? `https://www.youtube.com/watch?v=${vid.youtubeId}` : ''));
    setThumbnailUrl(vid.thumbnailUrl);
    setDuration(vid.duration || '05:00');
    setCategory(vid.category);
    setDescription(vid.description);
    setVideoMetadata(null);
    setThumbnailMetadata(null);
    resetVideoUpload();
    resetThumbnailUpload();
    setIsModalOpen(true);
  };

  const handleSave = (e: React.FormEvent) => {
    e.preventDefault();

    // Validate the video source before publishing: an uploaded file provides a
    // Cloudinary URL automatically, but a manually pasted URL must be checked.
    const sourceUrl = videoMetadata ? videoMetadata.secure_url : videoUrl.trim();
    if (!sourceUrl) {
      showToast('Please upload a video file or paste a valid video URL before publishing.');
      return;
    }
    if (!videoMetadata && !isValidHttpUrl(sourceUrl)) {
      showToast('The video URL is invalid. Please paste a valid https:// URL.');
      return;
    }

    // Validate the thumbnail URL when manually provided (uploaded thumbnails are trusted).
    const finalThumbnail = thumbnailMetadata ? thumbnailMetadata.secure_url : thumbnailUrl.trim() || 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&q=80';
    if (!thumbnailMetadata && finalThumbnail && !isValidHttpUrl(finalThumbnail)) {
      showToast('The thumbnail URL is invalid. Please paste a valid https:// URL.');
      return;
    }

    const videoData: any = {
      title: title.trim(),
      duration: duration.trim() || '05:00',
      category: category.trim(),
      description: description.trim(),
      thumbnailUrl: finalThumbnail
    };

    // Add Cloudinary metadata if available
    if (videoMetadata) {
      videoData.videoUrl = videoMetadata.secure_url;
      videoData.public_id = videoMetadata.public_id;
      videoData.resource_type = videoMetadata.resource_type;
      videoData.format = videoMetadata.format;
      videoData.bytes = videoMetadata.bytes;
      videoData.upload_date = videoMetadata.created_at;
    } else {
      videoData.videoUrl = videoUrl.trim();
    }

    // Add thumbnail metadata if available
    if (thumbnailMetadata) {
      videoData.thumbnailUrl = thumbnailMetadata.secure_url;
      videoData.thumbnail_public_id = thumbnailMetadata.public_id;
      videoData.thumbnail_resource_type = thumbnailMetadata.resource_type;
    }

    if (editingVideo) {
      updateVideoItem(editingVideo.id, videoData);
    } else {
      addVideoItem(videoData);
    }
    setIsModalOpen(false);
  };

  const categoriesList = ['all', ...Array.from(new Set(videos.map(v => v.category)))];

  const filteredVideos = videos.filter(v => {
    const matchesCat = selectedCategory === 'all' || v.category === selectedCategory;
    const matchesSearch = v.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
                          v.description.toLowerCase().includes(searchQuery.toLowerCase());
    return matchesCat && matchesSearch;
  });

  const { currentPage, totalPages, pageItems, goToPage, goToFirstPage } = usePagination(filteredVideos, 6);

  // Reset to first page when search/category filters change
  useEffect(() => {
    goToFirstPage();
  }, [searchQuery, selectedCategory, goToFirstPage]);

  return (
    <AdminLayout
      title="Video Showcase Management"
      subtitle="Upload video files directly from your desktop or enter video links to feature on the website"
    >
      <div className="space-y-6">

        {/* Action Header */}
        <div className="bg-white p-5 rounded-2xl border border-amber-200 shadow-sm flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="space-y-1">
            <h2 className="font-serif font-extrabold text-lg text-amber-950 flex items-center gap-2">
              <Film className="w-5 h-5 text-amber-700" />
              <span>Media Library ({videos.length} Videos)</span>
            </h2>
            <p className="text-xs text-stone-600 font-serif">Upload video documentaries from desktop or link external video media</p>
          </div>

          <Button
            onClick={handleOpenAddModal}
            variant="accent"
            size="lg"
            className="shrink-0 active:scale-95"
          >
            <Plus className="w-4 h-4" />
            <span>Add New Video</span>
          </Button>
        </div>

        {/* Search & Filter Bar */}
        <div className="flex flex-col md:flex-row gap-3 items-center justify-between bg-[#fcf8f2] p-4 rounded-2xl border border-amber-200">
          <SearchInput
            placeholder="Search videos by title or description..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
          />

          <div className="flex flex-wrap gap-1.5 w-full md:w-auto">
            {categoriesList.map(cat => (
              <FilterPill
                key={cat}
                active={selectedCategory === cat}
                onClick={() => setSelectedCategory(cat)}
                className="capitalize"
              >
                {cat}
              </FilterPill>
            ))}
          </div>
        </div>

        {/* Videos Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {pageItems.map((vid) => {
            const vUrl = vid.videoUrl || (vid.youtubeId ? `https://www.youtube.com/watch?v=${vid.youtubeId}` : '');
            const isUploaded = isDirectVideo(vUrl);
            return (
              <div
                key={vid.id}
                className="bg-white rounded-2xl border border-amber-200 overflow-hidden shadow-sm hover:shadow-md transition-shadow flex flex-col justify-between group"
              >
                <div>
                  <div className="relative h-48 overflow-hidden bg-stone-900">
                    <img src={vid.thumbnailUrl} alt={vid.title} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300" />
                    <div className="absolute inset-0 bg-black/30 flex items-center justify-center">
                      <div className="w-10 h-10 rounded-full bg-amber-500 text-amber-950 flex items-center justify-center shadow-lg">
                        <Play className="w-4 h-4 fill-amber-950 ml-0.5" />
                      </div>
                    </div>
                    <span className="absolute top-3 left-3 bg-amber-950/90 text-amber-200 text-[10px] font-extrabold px-2.5 py-0.5 rounded-md border border-amber-600/40">
                      {vid.category}
                    </span>
                    <span className="absolute bottom-3 right-3 bg-black/80 text-white text-[10px] font-mono px-2 py-0.5 rounded">
                      {vid.duration}
                    </span>
                  </div>

                  <div className="p-4 space-y-2">
                    <div className="flex items-center justify-between">
                      <h3 className="font-serif font-extrabold text-amber-950 text-sm leading-snug">{vid.title}</h3>
                    </div>
                    <p className="text-stone-600 text-xs font-serif line-clamp-2">{vid.description}</p>
                    <div className="text-[10px] text-stone-500 font-mono flex items-center gap-1.5 pt-1">
                      <span className={`px-2 py-0.5 rounded font-bold ${isUploaded ? 'bg-emerald-100 text-emerald-900' : 'bg-amber-100 text-amber-900'}`}>
                        {isUploaded ? 'Desktop Upload' : 'Video Link'}
                      </span>
                    </div>
                  </div>
                </div>

                <div className="p-3 bg-stone-50 border-t border-amber-200 flex items-center justify-between gap-2">
                  <span className="text-[11px] text-amber-800 font-serif font-bold inline-flex items-center gap-1">
                    <Video className="w-3.5 h-3.5" />
                    <span>Duration: {vid.duration}</span>
                  </span>

                  <div className="flex items-center gap-1">
                    <Button
                      onClick={() => handleOpenEditModal(vid)}
                      variant="iconAmberText"
                      size="iconSm"
                      title="Edit Video"
                    >
                      <Edit className="w-3.5 h-3.5 text-amber-800" />
                      <span className="hidden xs:inline">Edit</span>
                    </Button>

                    <Button
                      onClick={() => setDeleteConfirm({ id: vid.id, title: vid.title })}
                      variant="iconRoseText"
                      size="iconSm"
                      title="Delete Video"
                    >
                      <Trash2 className="w-3.5 h-3.5 text-rose-700" />
                    </Button>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
        <Pagination currentPage={currentPage} totalPages={totalPages} onPageChange={goToPage} />

        {/* Modal Form for Add/Edit Video */}
        <Modal
          open={isModalOpen}
          onClose={() => setIsModalOpen(false)}
          title={editingVideo ? 'Edit Video Tour' : 'Add New Video Tour'}
          icon={<Film className="w-5 h-5 text-amber-700" />}
          variant="dialog"
          size="lg"
          animate
        >
          <form onSubmit={handleSave} className="space-y-4 font-serif text-xs">
            <Input
              label="Video Title *"
              labelClassName="block text-stone-800 font-bold mb-1"
              variant="cream"
              required
              placeholder="e.g. Paro Taktsang Tiger's Nest 4K Aerial Documentary"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
            />

                    {/* Desktop Video Upload OR URL */}
                    <div className="space-y-2 bg-[#fcf8f2] border border-amber-300 rounded-2xl p-4">
                      <label className="block text-amber-950 font-extrabold">Add Video File from Desktop or Video URL *</label>
                      
                      <div className="flex flex-col sm:flex-row gap-2">
                        <label className={`px-4 py-2.5 rounded-xl font-bold cursor-pointer inline-flex items-center justify-center gap-2 shadow-xs shrink-0 ${isVideoUploading ? 'bg-amber-400 text-amber-950' : 'bg-amber-700 hover:bg-amber-800 text-white'}`}>
                          {isVideoUploading ? (
                            <>
                              <Loader2 className="w-4 h-4 animate-spin" />
                              <span>Uploading {videoUploadProgress ? `${Math.round(videoUploadProgress.percentage)}%` : '...'}</span>
                            </>
                          ) : (
                            <>
                              <Upload className="w-4 h-4" />
                              <span>Select Video File from Desktop</span>
                            </>
                          )}
                          <input type="file" accept="video/*,.mp4,.webm,.ogg,.mov" onChange={handleVideoFileUpload} className="hidden" disabled={isVideoUploading} />
                        </label>

                        <span className="text-center sm:self-center font-bold text-stone-400 text-xs">OR</span>

                        <input
                          type="text"
                          placeholder="Paste direct video URL (e.g. https://...)"
                          value={videoUrl}
                          onChange={(e) => setVideoUrl(e.target.value)}
                          className="flex-1 bg-white border border-amber-300 rounded-xl p-2.5 text-stone-900 focus:outline-hidden focus:border-amber-600"
                          disabled={isVideoUploading}
                        />
                      </div>

                      {/* Upload Progress */}
                      {videoUploadProgress && (
                        <div className="mt-2 bg-amber-100 rounded-lg p-2">
                          <div className="flex items-center justify-between text-xs text-amber-900 mb-1">
                            <span>Uploading to Cloudinary...</span>
                            <span>{Math.round(videoUploadProgress.percentage)}%</span>
                          </div>
                          <div className="w-full bg-amber-200 rounded-full h-2">
                            <div 
                              className="bg-amber-600 h-2 rounded-full transition-all duration-300" 
                              style={{ width: `${videoUploadProgress.percentage}%` }}
                            />
                          </div>
                        </div>
                      )}

                      {/* Upload Error */}
                      {videoUploadError && (
                        <div className="mt-2 bg-rose-50 border border-rose-200 text-rose-800 text-xs p-2 rounded-lg">
                          {videoUploadError}
                        </div>
                      )}

                      {/* Video Player Preview if Video File / Data URL is selected */}
                      {videoUrl && !isVideoUploading && (
                        <div className="mt-3 bg-stone-900 rounded-xl p-2 space-y-2">
                          <span className="text-[10px] font-mono text-amber-300 font-bold block">Video Loaded Preview:</span>
                          {isDirectVideo(videoUrl) ? (
                            <video src={videoUrl} controls className="w-full max-h-48 rounded-lg object-contain bg-black" />
                          ) : (
                            <div className="text-amber-100 text-xs p-3 font-mono bg-stone-800 rounded-lg overflow-x-auto">
                              {videoUrl.substring(0, 100)}...
                            </div>
                          )}
                        </div>
                      )}
                    </div>

                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                      <Input
                        label="Category"
                        labelClassName="block text-stone-800 font-bold mb-1"
                        variant="cream"
                        placeholder="e.g. Documentary, Culture, Luxury Lodges, Trekking"
                        value={category}
                        onChange={(e) => setCategory(e.target.value)}
                      />

                      <Input
                        label="Duration (MM:SS or text)"
                        labelClassName="block text-stone-800 font-bold mb-1"
                        variant="cream"
                        placeholder="e.g. 04:30 or 10 mins"
                        value={duration}
                        onChange={(e) => setDuration(e.target.value)}
                      />
                    </div>

                    {/* Thumbnail Image URL or Upload */}
                    <div className="space-y-2">
                      <label className="block text-stone-800 font-bold mb-1">Thumbnail Image</label>
                      <div className="flex gap-2 items-center">
                        <input
                          type="text"
                          placeholder="Thumbnail Image URL (e.g. https://...)"
                          value={thumbnailUrl}
                          onChange={(e) => setThumbnailUrl(e.target.value)}
                          className="flex-1 bg-[#fcf8f2] border border-amber-300 rounded-xl p-2.5 text-stone-900 focus:outline-hidden focus:border-amber-600"
                          disabled={isThumbnailUploading}
                        />
                        <label className={`px-3 py-2.5 rounded-xl font-bold cursor-pointer inline-flex items-center gap-1 shrink-0 ${isThumbnailUploading ? 'bg-amber-400 text-amber-950' : 'bg-amber-100 hover:bg-amber-200 text-amber-900'}`}>
                          {isThumbnailUploading ? (
                            <>
                              <Loader2 className="w-4 h-4 animate-spin" />
                              <span>{thumbnailUploadProgress ? `${Math.round(thumbnailUploadProgress.percentage)}%` : '...'}</span>
                            </>
                          ) : (
                            <>
                              <Upload className="w-4 h-4" />
                              <span>Upload Desktop Thumbnail</span>
                            </>
                          )}
                          <input type="file" accept="image/*,.png,.jpg,.jpeg,.webp" onChange={handleThumbnailUpload} className="hidden" disabled={isThumbnailUploading} />
                        </label>
                      </div>
                      
                      {/* Thumbnail Upload Progress */}
                      {thumbnailUploadProgress && (
                        <div className="bg-amber-100 rounded-lg p-2">
                          <div className="flex items-center justify-between text-xs text-amber-900 mb-1">
                            <span>Uploading thumbnail...</span>
                            <span>{Math.round(thumbnailUploadProgress.percentage)}%</span>
                          </div>
                          <div className="w-full bg-amber-200 rounded-full h-2">
                            <div 
                              className="bg-amber-600 h-2 rounded-full transition-all duration-300" 
                              style={{ width: `${thumbnailUploadProgress.percentage}%` }}
                            />
                          </div>
                        </div>
                      )}

                      {/* Thumbnail Upload Error */}
                      {thumbnailUploadError && (
                        <div className="bg-rose-50 border border-rose-200 text-rose-800 text-xs p-2 rounded-lg">
                          {thumbnailUploadError}
                        </div>
                      )}

                      {thumbnailUrl && !isThumbnailUploading && (
                        <img src={thumbnailUrl} alt="Thumbnail Preview" className="w-24 h-16 object-cover rounded-lg border border-amber-300 mt-2" />
                      )}
                    </div>

                    <TextArea
                      label="Video Description"
                      labelClassName="block text-stone-800 font-bold mb-1"
                      variant="cream"
                      rows={3}
                      placeholder="Short summary of what this video showcases..."
                      value={description}
                      onChange={(e) => setDescription(e.target.value)}
                    />

                    <div className="flex items-center justify-end gap-3 pt-3 border-t border-amber-200">
                      <Button type="button" variant="outline" size="mdXl" onClick={() => setIsModalOpen(false)}>
                        Cancel
                      </Button>
                      <Button type="submit" variant="submitAccent" size="submitWide">
                        <Check className="w-4 h-4" />
                        <span>{editingVideo ? 'Update Video' : 'Publish Video'}</span>
                      </Button>
                    </div>
                  </form>
        </Modal>

        {/* Delete Confirmation Modal */}
        <ConfirmDialog
          open={Boolean(deleteConfirm)}
          dense
          className="font-serif"
          title="Delete Video?"
          message={(
            <span>
              Are you sure you want to delete <span className="font-bold text-rose-900">"{deleteConfirm?.title}"</span>?
            </span>
          )}
          onCancel={() => setDeleteConfirm(null)}
          onConfirm={() => {
            if (deleteConfirm) deleteVideoItem(deleteConfirm.id);
            setDeleteConfirm(null);
          }}
        />

      </div>
    </AdminLayout>
  );
};
